import type {
  User, Ride, ChatThread, Notification, MonthlySaving, Rating, RideRequest,
} from './types';

// ─── Helpers ───────────────────────────────────────────────────────────────

const avatar = (seed: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf`;

// ─── Users ─────────────────────────────────────────────────────────────────

export const USERS: User[] = [
  {
    id: 'u1',
    name: 'Hamza Tariq',
    phone: '+923001234567',
    email: 'hamza.tariq@lums.edu.pk',
    gender: 'male',
    city: 'Lahore',
    university: 'LUMS',
    avatar: avatar('Hamza'),
    bio: 'CS final year at LUMS. Daily commute DHA ↔ LUMS.',
    rating: 4.8,
    totalRides: 47,
    ridesOffered: 12,
    ridesTaken: 35,
    totalSavedPKR: 18400,
    memberSince: '2024-02-15',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2024-02-20' },
      { type: 'university', status: 'verified', verifiedAt: '2024-02-22', institution: 'LUMS' },
    ],
    trustedContacts: [
      { id: 'tc1', name: 'Ammi (Fatima Tariq)', phone: '+923001111111', relation: 'Mother', isPrimary: true },
    ],
    vehicle: { make: 'Honda', model: 'City', year: 2021, color: 'White', plate: 'LEB-1234' },
  },
  {
    id: 'u2',
    name: 'Sana Rehman',
    phone: '+923011234567',
    email: 'sana.rehman@agency.pk',
    gender: 'female',
    city: 'Lahore',
    workplace: 'Dentsu Creative Lahore',
    avatar: avatar('Sana'),
    bio: 'Marketing exec at Dentsu. Gulberg ↔ MM Alam daily.',
    rating: 4.9,
    totalRides: 89,
    ridesOffered: 0,
    ridesTaken: 89,
    totalSavedPKR: 34200,
    memberSince: '2023-08-10',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2023-08-15' },
      { type: 'workplace', status: 'verified', verifiedAt: '2023-08-18', institution: 'Dentsu Creative' },
    ],
    trustedContacts: [
      { id: 'tc2', name: 'Sara Rehman', phone: '+923012222222', relation: 'Sister', isPrimary: true },
      { id: 'tc3', name: 'Abba Jan', phone: '+923013333333', relation: 'Father', isPrimary: false },
    ],
  },
  {
    id: 'u3',
    name: 'Bilal Chaudhry',
    phone: '+923021234567',
    email: 'bilal.chaudhry@techco.pk',
    gender: 'male',
    city: 'Lahore',
    workplace: 'Systems Limited',
    avatar: avatar('Bilal'),
    bio: 'Sr. engineer at Systems Ltd. Johar Town ↔ Arfa Tech Park.',
    rating: 4.7,
    totalRides: 134,
    ridesOffered: 98,
    ridesTaken: 36,
    totalSavedPKR: 52800,
    memberSince: '2023-04-05',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2023-04-10' },
      { type: 'workplace', status: 'verified', verifiedAt: '2023-04-12', institution: 'Systems Limited' },
    ],
    trustedContacts: [],
    vehicle: { make: 'Toyota', model: 'Corolla', year: 2022, color: 'Silver', plate: 'LDA-5678' },
  },
  {
    id: 'u4',
    name: 'Saira Malik',
    phone: '+923031234567',
    email: 'saira.malik@kinnaird.edu.pk',
    gender: 'female',
    city: 'Lahore',
    university: 'Kinnaird College',
    avatar: avatar('Saira'),
    bio: 'Psychology student at Kinnaird. Bahria Town ↔ Campus.',
    rating: 4.6,
    totalRides: 23,
    ridesOffered: 0,
    ridesTaken: 23,
    totalSavedPKR: 8600,
    memberSince: '2024-07-20',
    verifications: [
      { type: 'university', status: 'verified', verifiedAt: '2024-07-25', institution: 'Kinnaird College' },
      { type: 'cnic', status: 'pending' },
    ],
    trustedContacts: [
      { id: 'tc4', name: 'Abba (Tariq Malik)', phone: '+923034444444', relation: 'Father', isPrimary: true },
    ],
  },
  {
    id: 'u5',
    name: 'Ahmed Farooq',
    phone: '+923041234567',
    gender: 'male',
    city: 'Lahore',
    university: 'FAST NUCES',
    avatar: avatar('Ahmed'),
    rating: 4.5,
    totalRides: 62,
    ridesOffered: 28,
    ridesTaken: 34,
    totalSavedPKR: 22100,
    memberSince: '2023-11-01',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2023-11-05' },
      { type: 'university', status: 'verified', verifiedAt: '2023-11-08', institution: 'FAST NUCES' },
    ],
    trustedContacts: [],
    vehicle: { make: 'Suzuki', model: 'Alto', year: 2020, color: 'Red', plate: 'LGU-9012' },
  },
  {
    id: 'u6',
    name: 'Fatima Hassan',
    phone: '+923051234567',
    email: 'fatima.h@nust.edu.pk',
    gender: 'female',
    city: 'Islamabad',
    university: 'NUST',
    avatar: avatar('Fatima'),
    bio: 'MBA student at NUST. F-10 ↔ H-12 NUST campus.',
    rating: 4.9,
    totalRides: 41,
    ridesOffered: 15,
    ridesTaken: 26,
    totalSavedPKR: 15300,
    memberSince: '2024-01-08',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2024-01-12' },
      { type: 'university', status: 'verified', verifiedAt: '2024-01-14', institution: 'NUST' },
    ],
    trustedContacts: [
      { id: 'tc5', name: 'Hassan Bhai', phone: '+923055555555', relation: 'Brother', isPrimary: true },
    ],
    vehicle: { make: 'Kia', model: 'Picanto', year: 2023, color: 'Blue', plate: 'ISB-3456' },
  },
  {
    id: 'u7',
    name: 'Usman Sheikh',
    phone: '+923061234567',
    gender: 'male',
    city: 'Karachi',
    workplace: 'HBL Bank',
    avatar: avatar('Usman'),
    bio: 'Banker at HBL. Clifton ↔ I.I. Chundrigar Road.',
    rating: 4.4,
    totalRides: 78,
    ridesOffered: 45,
    ridesTaken: 33,
    totalSavedPKR: 29700,
    memberSince: '2023-06-15',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2023-06-20' },
      { type: 'workplace', status: 'verified', verifiedAt: '2023-06-22', institution: 'HBL Bank' },
    ],
    trustedContacts: [],
    vehicle: { make: 'Honda', model: 'Civic', year: 2020, color: 'Black', plate: 'KAA-7890' },
  },
  {
    id: 'u8',
    name: 'Aisha Nawaz',
    phone: '+923071234567',
    email: 'aisha.nawaz@iba.edu.pk',
    gender: 'female',
    city: 'Karachi',
    university: 'IBA Karachi',
    avatar: avatar('Aisha'),
    bio: 'IBA Finance student. Gulshan ↔ IBA City Campus.',
    rating: 4.8,
    totalRides: 31,
    ridesOffered: 8,
    ridesTaken: 23,
    totalSavedPKR: 11200,
    memberSince: '2024-03-22',
    verifications: [
      { type: 'cnic', status: 'verified', verifiedAt: '2024-03-25' },
      { type: 'university', status: 'verified', verifiedAt: '2024-03-26', institution: 'IBA Karachi' },
    ],
    trustedContacts: [
      { id: 'tc6', name: 'Mama', phone: '+923076666666', relation: 'Mother', isPrimary: true },
    ],
    vehicle: { make: 'Suzuki', model: 'WagonR', year: 2022, color: 'White', plate: 'KBB-2345' },
  },
];

// Current logged-in user (Hamza by default)
export const CURRENT_USER = USERS[0];

// ─── Rides ─────────────────────────────────────────────────────────────────

export const RIDES: Ride[] = [
  {
    id: 'r1',
    driver: USERS[2], // Bilal
    context: 'city',
    from: { label: 'Johar Town, Block D', city: 'Lahore', lat: 31.469, lng: 74.274 },
    to: { label: 'Arfa Software Technology Park', city: 'Lahore', lat: 31.549, lng: 74.343 },
    date: '2025-05-21',
    time: '08:30',
    seats: 3,
    seatsLeft: 2,
    pricePKR: 180,
    genderPreference: 'any',
    requireCnic: true,
    requireUniversity: false,
    status: 'upcoming',
    passengers: [USERS[3]],
    vehicle: USERS[2].vehicle,
    driverNote: 'AC on. No food or smoking. I leave sharp at 8:30.',
    estimatedMinutes: 28,
    distanceKm: 12,
    recurring: { type: 'weekdays' },
    baggageAllowed: 'small',
  },
  {
    id: 'r2',
    driver: USERS[5], // Fatima
    context: 'city',
    from: { label: 'Gulberg III, Main Blvd', city: 'Lahore', lat: 31.520, lng: 74.358 },
    to: { label: 'MM Alam Road', city: 'Lahore', lat: 31.518, lng: 74.352 },
    date: '2025-05-21',
    time: '09:00',
    seats: 2,
    seatsLeft: 1,
    pricePKR: 120,
    genderPreference: 'female',
    requireCnic: false,
    requireUniversity: false,
    status: 'upcoming',
    passengers: [],
    vehicle: USERS[5].vehicle,
    driverNote: 'Female passengers only. Daily recurring ride.',
    estimatedMinutes: 12,
    distanceKm: 4,
    recurring: { type: 'weekdays' },
    baggageAllowed: 'none',
  },
  {
    id: 'r3',
    driver: USERS[4], // Ahmed
    context: 'campus',
    from: { label: 'DHA Phase 5, Y-Block', city: 'Lahore', lat: 31.468, lng: 74.407 },
    to: { label: 'LUMS, DHA', city: 'Lahore', lat: 31.395, lng: 74.264 },
    date: '2025-05-21',
    time: '07:45',
    seats: 4,
    seatsLeft: 3,
    pricePKR: 150,
    genderPreference: 'any',
    requireCnic: false,
    requireUniversity: true,
    status: 'upcoming',
    passengers: [USERS[3]],
    vehicle: USERS[4].vehicle,
    driverNote: 'Students only. I stop at FAST NUCES first then LUMS.',
    estimatedMinutes: 35,
    distanceKm: 18,
    stops: [{ label: 'FAST NUCES', city: 'Lahore', lat: 31.481, lng: 74.290 }],
    recurring: { type: 'custom', days: ['Mon', 'Wed', 'Fri'] },
    baggageAllowed: 'small',
  },
  {
    id: 'r4',
    driver: USERS[2], // Bilal
    context: 'intercity',
    from: { label: 'Thokar Niaz Baig, Lahore', city: 'Lahore', lat: 31.420, lng: 74.194 },
    to: { label: 'Islamabad Toll Plaza', city: 'Islamabad', lat: 33.684, lng: 73.047 },
    date: '2025-05-23',
    time: '06:00',
    seats: 3,
    seatsLeft: 2,
    pricePKR: 2200,
    genderPreference: 'any',
    requireCnic: true,
    requireUniversity: false,
    status: 'upcoming',
    passengers: [USERS[1]],
    vehicle: USERS[2].vehicle,
    driverNote: 'Motorway M-2 route. One stop at Bhera for fuel (15 min).',
    estimatedMinutes: 240,
    distanceKm: 390,
    baggageAllowed: 'large',
  },
  {
    id: 'r5',
    driver: USERS[0], // Hamza
    context: 'campus',
    from: { label: 'DHA Phase 6, Block L', city: 'Lahore', lat: 31.462, lng: 74.420 },
    to: { label: 'LUMS, Sector U', city: 'Lahore', lat: 31.395, lng: 74.264 },
    date: '2025-05-21',
    time: '08:00',
    seats: 3,
    seatsLeft: 2,
    pricePKR: 130,
    genderPreference: 'any',
    requireCnic: false,
    requireUniversity: true,
    status: 'upcoming',
    passengers: [],
    vehicle: USERS[0].vehicle,
    driverNote: 'LUMS students only. Punctuality appreciated.',
    estimatedMinutes: 30,
    distanceKm: 15,
    recurring: { type: 'weekdays' },
    baggageAllowed: 'small',
  },
  {
    id: 'r6',
    driver: USERS[7], // Aisha
    context: 'campus',
    from: { label: 'Gulshan-e-Iqbal, Block 13', city: 'Karachi', lat: 24.921, lng: 67.082 },
    to: { label: 'IBA City Campus', city: 'Karachi', lat: 24.865, lng: 67.010 },
    date: '2025-05-21',
    time: '08:15',
    seats: 2,
    seatsLeft: 1,
    pricePKR: 200,
    genderPreference: 'female',
    requireCnic: false,
    requireUniversity: true,
    status: 'upcoming',
    passengers: [],
    vehicle: USERS[7].vehicle,
    driverNote: 'IBA students only. Female preferred.',
    estimatedMinutes: 40,
    distanceKm: 14,
    recurring: { type: 'weekdays' },
    baggageAllowed: 'small',
  },
  {
    id: 'r7',
    driver: USERS[6], // Usman
    context: 'city',
    from: { label: 'Clifton Block 8', city: 'Karachi', lat: 24.812, lng: 67.030 },
    to: { label: 'I.I. Chundrigar Road, HBL HQ', city: 'Karachi', lat: 24.864, lng: 67.010 },
    date: '2025-05-21',
    time: '08:45',
    seats: 3,
    seatsLeft: 2,
    pricePKR: 250,
    genderPreference: 'any',
    requireCnic: true,
    requireUniversity: false,
    status: 'upcoming',
    passengers: [],
    vehicle: USERS[6].vehicle,
    driverNote: 'Corporate professionals preferred. I park at HBL Tower.',
    estimatedMinutes: 25,
    distanceKm: 10,
    recurring: { type: 'weekdays' },
    baggageAllowed: 'small',
  },
  {
    id: 'r8',
    driver: USERS[4], // Ahmed
    context: 'city',
    from: { label: 'Bahria Town Gate 1, Lahore', city: 'Lahore', lat: 31.351, lng: 74.178 },
    to: { label: 'Ferozepur Road, Canal Bank', city: 'Lahore', lat: 31.466, lng: 74.317 },
    date: '2025-05-21',
    time: '07:30',
    seats: 3,
    seatsLeft: 2,
    pricePKR: 160,
    genderPreference: 'any',
    requireCnic: false,
    requireUniversity: false,
    status: 'upcoming',
    passengers: [USERS[1]],
    vehicle: USERS[4].vehicle,
    estimatedMinutes: 45,
    distanceKm: 22,
    baggageAllowed: 'small',
  },
  // Completed rides for history
  {
    id: 'r9',
    driver: USERS[2],
    context: 'city',
    from: { label: 'Johar Town', city: 'Lahore', lat: 31.469, lng: 74.274 },
    to: { label: 'Arfa Tech Park', city: 'Lahore', lat: 31.549, lng: 74.343 },
    date: '2025-05-19',
    time: '08:30',
    seats: 3,
    seatsLeft: 0,
    pricePKR: 180,
    genderPreference: 'any',
    requireCnic: true,
    requireUniversity: false,
    status: 'completed',
    passengers: [USERS[0], USERS[3]],
    vehicle: USERS[2].vehicle,
    estimatedMinutes: 28,
    distanceKm: 12,
    baggageAllowed: 'small',
  },
  {
    id: 'r10',
    driver: USERS[0], // Hamza offered this
    context: 'campus',
    from: { label: 'DHA Phase 6', city: 'Lahore', lat: 31.462, lng: 74.420 },
    to: { label: 'LUMS', city: 'Lahore', lat: 31.395, lng: 74.264 },
    date: '2025-05-16',
    time: '08:00',
    seats: 3,
    seatsLeft: 0,
    pricePKR: 130,
    genderPreference: 'any',
    requireCnic: false,
    requireUniversity: true,
    status: 'completed',
    passengers: [USERS[3], USERS[4]],
    vehicle: USERS[0].vehicle,
    estimatedMinutes: 30,
    distanceKm: 15,
    baggageAllowed: 'small',
  },
];

// ─── Chat Threads ───────────────────────────────────────────────────────────

export const CHAT_THREADS: ChatThread[] = [
  {
    id: 'ct1',
    participants: [USERS[0], USERS[2]],
    rideId: 'r1',
    updatedAt: '2025-05-20T09:15:00Z',
    messages: [
      { id: 'm1', senderId: 'u3', text: 'Assalam o Alaikum! Aap kal 8:30 pe ready honge?', timestamp: '2025-05-20T08:50:00Z', read: true, type: 'text' },
      { id: 'm2', senderId: 'u1', text: 'Walaikum Assalam! Haan bilkul, main 8:25 pe pickup point pe hoga.', timestamp: '2025-05-20T09:00:00Z', read: true, type: 'text' },
      { id: 'm3', senderId: 'u3', text: 'Theek hai. Meri car silver Corolla hai, plate LDA-5678.', timestamp: '2025-05-20T09:05:00Z', read: true, type: 'text' },
      { id: 'm4', senderId: 'u1', text: 'Got it! See you tomorrow 👍', timestamp: '2025-05-20T09:10:00Z', read: true, type: 'text' },
      { id: 'm5', senderId: 'u3', text: 'Weather dekhna, might be traffic on Canal Road.', timestamp: '2025-05-20T09:15:00Z', read: false, type: 'text' },
    ],
  },
  {
    id: 'ct2',
    participants: [USERS[0], USERS[1]],
    rideId: 'r4',
    updatedAt: '2025-05-19T14:30:00Z',
    messages: [
      { id: 'm6', senderId: 'u2', text: 'Hi Hamza! Main Islamabad trip ke liye join karna chahti hoon.', timestamp: '2025-05-19T13:00:00Z', read: true, type: 'text' },
      { id: 'm7', senderId: 'u1', text: 'Sure Sana baji! Request send kar dein, main accept kar leta hoon.', timestamp: '2025-05-19T13:15:00Z', read: true, type: 'text' },
      { id: 'm8', senderId: 'u2', text: 'Done! Bhera pe koi dhaaba hai theek sa? 😄', timestamp: '2025-05-19T14:20:00Z', read: true, type: 'text' },
      { id: 'm9', senderId: 'u1', text: 'Haha haan! Motorway Nihari is good. We can stop there.', timestamp: '2025-05-19T14:30:00Z', read: true, type: 'text' },
    ],
  },
  {
    id: 'ct3',
    participants: [USERS[0], USERS[4]],
    rideId: 'r3',
    updatedAt: '2025-05-20T07:00:00Z',
    messages: [
      { id: 'm10', senderId: 'u5', text: 'Hamza bhai, kal LUMS ride ke liye seat hai?', timestamp: '2025-05-19T20:00:00Z', read: true, type: 'text' },
      { id: 'm11', senderId: 'u1', text: 'Haan 2 seats baqi hain, request daal do.', timestamp: '2025-05-19T20:30:00Z', read: true, type: 'text' },
      { id: 'm12', senderId: 'u5', text: 'Request bhej di! Main DHA Phase 5 Main Blvd pe hoga.', timestamp: '2025-05-19T20:35:00Z', read: true, type: 'text' },
      { id: 'm13', senderId: 'u1', text: '👍 Accepted. 7:45 sharp.', timestamp: '2025-05-20T07:00:00Z', read: false, type: 'text' },
    ],
  },
];

// ─── Notifications ──────────────────────────────────────────────────────────

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'request_accepted',
    title: 'Ride Confirmed! 🎉',
    body: 'Bilal Chaudhry has accepted your request for Johar Town → Arfa Tech Park tomorrow at 8:30 AM.',
    read: false,
    createdAt: '2025-05-20T10:00:00Z',
    rideId: 'r1',
  },
  {
    id: 'n2',
    type: 'ride_reminder',
    title: 'Ride tomorrow at 7:45 AM',
    body: 'Your ride from DHA Phase 5 to LUMS is tomorrow. Ahmed Farooq is your driver.',
    read: false,
    createdAt: '2025-05-20T18:00:00Z',
    rideId: 'r3',
  },
  {
    id: 'n3',
    type: 'request_received',
    title: 'New Ride Request',
    body: 'Saira Malik wants to join your DHA → LUMS ride on Wednesday.',
    read: true,
    createdAt: '2025-05-19T15:00:00Z',
    rideId: 'r5',
  },
  {
    id: 'n4',
    type: 'system',
    title: 'Verification Complete ✓',
    body: 'Your LUMS university email has been verified. You can now offer and join campus rides.',
    read: true,
    createdAt: '2025-05-18T11:00:00Z',
  },
];

// ─── Monthly Savings ────────────────────────────────────────────────────────

export const MONTHLY_SAVINGS: MonthlySaving[] = [
  { month: 'Nov', year: 2024, savedPKR: 3200, rides: 14, co2Kg: 9.8 },
  { month: 'Dec', year: 2024, savedPKR: 2400, rides: 10, co2Kg: 7.2 },
  { month: 'Jan', year: 2025, savedPKR: 4100, rides: 18, co2Kg: 12.6 },
  { month: 'Feb', year: 2025, savedPKR: 3800, rides: 16, co2Kg: 11.4 },
  { month: 'Mar', year: 2025, savedPKR: 4600, rides: 21, co2Kg: 14.1 },
  { month: 'Apr', year: 2025, savedPKR: 3900, rides: 17, co2Kg: 11.8 },
  { month: 'May', year: 2025, savedPKR: 2800, rides: 12, co2Kg: 8.6 },
];

// ─── Ride Requests ──────────────────────────────────────────────────────────

export const RIDE_REQUESTS: RideRequest[] = [
  {
    id: 'rq1',
    rideId: 'r5',
    passenger: USERS[3],
    status: 'pending',
    seats: 1,
    note: 'Assalam o Alaikum! Main Kinnaird se hoon, same area hai.',
    requestedAt: '2025-05-19T15:00:00Z',
  },
];

// ─── Ratings ───────────────────────────────────────────────────────────────

export const RATINGS: Rating[] = [
  {
    id: 'rt1',
    rideId: 'r9',
    reviewer: USERS[0],
    reviewee: USERS[2],
    stars: 5,
    tags: ['Punctual', 'Safe driving', 'Clean car'],
    comment: 'Bilal bhai bahut professional hain. Time pe the aur AC perfect tha!',
    createdAt: '2025-05-19T18:00:00Z',
  },
  {
    id: 'rt2',
    rideId: 'r9',
    reviewer: USERS[2],
    reviewee: USERS[0],
    stars: 5,
    tags: ['Punctual', 'Polite'],
    comment: 'Great passenger, on time and good company.',
    createdAt: '2025-05-19T18:30:00Z',
  },
];

// ─── Popular Routes ─────────────────────────────────────────────────────────

export const POPULAR_ROUTES = [
  { from: 'DHA Phase 5', to: 'LUMS', city: 'Lahore', rides: 34, avgPKR: 140 },
  { from: 'Gulberg', to: 'MM Alam Road', city: 'Lahore', rides: 28, avgPKR: 110 },
  { from: 'Johar Town', to: 'Arfa Tech Park', city: 'Lahore', rides: 21, avgPKR: 175 },
  { from: 'Bahria Town', to: 'Ferozepur Road', city: 'Lahore', rides: 18, avgPKR: 155 },
  { from: 'Lahore', to: 'Islamabad', city: 'Intercity', rides: 15, avgPKR: 2100 },
  { from: 'Clifton', to: 'I.I. Chundrigar Rd', city: 'Karachi', rides: 12, avgPKR: 240 },
];
